# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Handle all updates, but split them into separate PRs for major and minor/patch
  - package-ecosystem: "pip"
    directory: "/"  # Root directory where the Python dependency files are located
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    # Group major and minor updates separately
    groups:
      minor-updates:
        patterns:
          - "requirements*.txt"
          - "requirements*.in"
          - "setup.py"
          - "setup.cfg"
          - "pyproject.toml"
        labels:
          - "minor-update"
        ignore:
          - update-types: ["version-update:semver-major"]  # Ignore major updates in this group

      major-updates:
        patterns:
          - "requirements*.txt"
          - "requirements*.in"
          - "setup.py"
          - "setup.cfg"
          - "pyproject.toml"
        labels:
          - "major-update"
        ignore:
          - update-types: ["version-update:semver-minor", "version-update:semver-patch"]  # Ignore minor/patch updates in this group
