coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0%
        informational: true
        paths:
          - "db"
          - "scripts"
          - "metamist/parser"
    patch:
      default:
        informational: true
ignore: "test/data/audit_fixtures/"
