name: sample-metadata-dev

channels:
  - cpg
  - bioconda
  - conda-forge
dependencies:
  - python=3.7
  - cpg-utils
# dev dependencies
  - black
  - flake8
  - flake8-bugbear
  - pre-commit
  - pylint
  - bump2version
  - pip
  - pip:
    - '-r requirements.txt'
