[project]
name = "metamist-root"
version = "7.14.0"
requires-python = "==3.14.*"
dependencies = [
    "backoff~=2.2",
    "cpg-utils>=5.5.0",
    "google-auth~=2.48",
    "click~=8.3",
    "gql[aiohttp,requests]~=4.0",
    "python-dateutil~=2.9",
    "requests~=2.32",
    "tabulate ~= 0.9.0",
    "urllib3 ~= 2.6",
    "aiohttp~=3.13",
    "async-lru~=2.1",
    "cloudpathlib~=0.23.0",
    "cryptography~=46.0",
    "duckdb~=1.4",
    "fastapi[all]~=0.128.0",
    "fsspec==2026.1.0",
    "google-cloud-bigquery~=3.40",
    "google-cloud-logging~=3.13",
    "google-cloud-pubsub~=2.34",
    "google-cloud-storage~=3.8",
    "pyarrow~=23.0",
    "slack-sdk~=3.39",
    "strawberry-graphql[fastapi]~=0.291.0",
    "uvicorn~=0.40.0",
    "psycopg[binary]~=3.3",
    "psycopg-pool~=3.3",
    "pytest~=9.0",
    "databases~=0.9.0",
]

[tool.ruff]
line-length = 88
# Make sure linting/formatting changes don't break compatibility with
# python 3.10 which is the min supported version for the metamist python package
target-version = "py310"

exclude = [
    "packages/metamist/src/metamist/api/*",
    "packages/metamist/src/metamist/apis/*",
    "packages/metamist/src/metamist/model/*",
    "packages/metamist/src/metamist/models/*",

]

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
select = [
    "E",        # pycodestyle errors - https://docs.astral.sh/ruff/rules/#error-e
    "D",        # pydocstyle - https://docs.astral.sh/ruff/rules/#pydocstyle-d
    "F",        # Pyflakes - https://docs.astral.sh/ruff/rules/#pyflakes-f
    "UP",       # pyupgrade - https://docs.astral.sh/ruff/rules/#pyupgrade-up
    "I",        # isort - https://docs.astral.sh/ruff/rules/#isort-i
    "N",        # pep8-naming - https://docs.astral.sh/ruff/rules/#pep8-naming-n
    "W",        # pycodestyle warnings - https://docs.astral.sh/ruff/rules/#warning-w
    "B",        # flake8-bugbear - https://docs.astral.sh/ruff/rules/#flake8-bugbear-b
    "A",        # flake8-builtins - https://docs.astral.sh/ruff/rules/#flake8-builtins-a
    "C4",       # flake8-comprehensions - https://docs.astral.sh/ruff/rules/#flake8-comprehensions-c4
    "PIE",      # flake8-pie - https://docs.astral.sh/ruff/rules/#flake8-pie-pie
    "T20",      # flake8-print - https://docs.astral.sh/ruff/rules/#flake8-print-t20
    "SIM",      # flake8-simplify - https://docs.astral.sh/ruff/rules/#flake8-simplify-sim
    "RET",      # flake8-return - https://docs.astral.sh/ruff/rules/#flake8-return-ret
    "ARG",      # flake8-unused-arguments - https://docs.astral.sh/ruff/rules/#flake8-unused-arguments-arg
    "PTH",      # flake8-use-pathlib - https://docs.astral.sh/ruff/rules/#flake8-use-pathlib-pth
    "PL",       # Pylint - https://docs.astral.sh/ruff/rules/#pylint-pl
    "Q",        # flake8-quotes - https://docs.astral.sh/ruff/rules/#flake8-quotes-q
    "BLE001",   # flake8-blind-except - https://docs.astral.sh/ruff/rules/#flake8-blind-except-ble001
    "RUF100",   # Disallow unused noqa - https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf
]

# Ignore some specific rules that we don't enforce in this project
ignore = [
    # line-too-long (handled by formatter)
    "E501",
    # f-string-without-interpolation (we allow f-strings that don't do any
    # formatting for consistent looks and for future safety)
    "F541",
    # Q003 ("Change outer quotes to avoid escaping inner quotes")
    "Q003",


    # Don't raise errors on shadowing of builtins, we do this a fair bit in the graphql
    # schema and the alternative is quite a messy syntax to specify the alternative field
    # name to return
    "A002",
    # Don't enforce usage of set literals, allow using set(a['id'] for a in b) as is sometimes
    # better for readability.
    "C401",
    # Allow function-call-in-default-argument
    # (This is used a bunch in FastAPI dependency injection)
    "B008",
    # Allow print statements, these are in lots of scripts so would be annoying to change
    "T201",
    # Allow assign before returning, can be useful for readability
    "RET504",

    # Ignore overly pedantic docstring errors. These would require lots of fixing
    # on existing code to become compliant and aren't that important
    "D400", # First line should end with a period
    "D415", # First line should end with a period, question mark, or exclamation point
    "D212", # Multi-line docstring summary should start at the first line
    "D200", # One-line docstring should fit on one line
    "D202", # No blank lines allowed after function docstring
    "D205", # 1 blank line required between summary line and description
    "D100", # Missing docstring in public module
    "D102", # Missing docstring in public method
    "D401", # First line of docstring should be in imperative mood
    "D413", # Missing blank line after last section
    "D107", # Missing docstring in __init__
    "D104", # Missing docstring in public package
    "D404", # First word of the docstring should not be "This"
    "D105", # Missing docstring in magic method
    "D209", # Multi-line docstring closing quotes should be on a separate line
    "D403", # First word of the docstring should be capitalized
    "D203", # 1 blank line required before class docstring, conflicts with D211

]


[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]


[tool.ruff.lint.pylint]
max-args = 10
max-branches = 20
max-statements = 100
max-locals = 25

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "double"
docstring-quotes = "double"

[tool.ruff.lint.isort]
section-order = ["future", "standard-library", "third-party", "hail", "cpg", "first-party", "local-folder"]
lines-after-imports = 2
force-single-line = false

[tool.ruff.lint.isort.sections]
hail = ["hail", "hailtop"]
cpg = ["analysis_runner", "cpg_infra", "cpg_utils", "cpg_workflows", "gnomad", "hail_scripts", "metamist"]

[dependency-groups]
dev = [
    "bump-my-version~=1.2",
    "coverage~=7.6",
    "functions-framework~=3.10",
    "openapi-generator-cli==5.3.0",
    "pre-commit~=4.5.1",
    "pytest~=9.0",
    "pytest-asyncio~=1.3",
    "pytest-cov~=7.0",
    "pytz>=2025.2",
    "testcontainers~=4.14",
    "httpx~=0.28.0",
    "pip-audit~=2.10",
    "strawberry-graphql[debug-server]~=0.291.0",
    "metamist",
    "ruff>=0.15.0",
]

[tool.uv]
package = false
constraint-dependencies = [
    "aiomysql~=0.3.0",
    "azure-core>=1.38.0",
    "filelock>=3.20.1",
    "pyasn1>=0.6.2",
    "python-multipart>=0.0.22",
    "starlette>=0.49.1",
    "virtualenv>=20.36.1",
    "werkzeug>=3.1.5"
]

[tool.uv.sources]
metamist = { path = "packages/metamist", editable = true }

[tool.coverage.run]
omit = [
    "test/*",
    "test/**/*",
    "packages/metamist/src/metamist/api/*",
    "packages/metamist/src/metamist/apis/*",
    "packages/metamist/src/metamist/model/*",
    "packages/metamist/src/metamist/models/*",
    "packages/metamist/src/metamist/*.py",
]
