secretsprovider: gcpkms://projects/metamist-488300/locations/australia-southeast1/keyRings/metamist_pulumi_secrets_keyring/cryptoKeys/metamist_pulumi_secrets
encryptedkey: CiQAelOKiUKO55T9/L58gQl4yuSCU6VRJMcuNAh377Foxf1qJvwSSQDdXNuFPODn1KcT+V++wl3SjTi181KXWF1fggSVGR7FS/NRHHmQrq58ggRKDoWjWxI5nUMiy5yDILQWyOmfOikK/L25EdznGSQ=
config:
  gcp:project: metamist-488300
  gcp:billing_project: metamist-488300
  gcp:user_project_override: 'true'
  gcp:region: australia-southeast1

  metamist:common:
    vpc_network: metamist-db
    vpc_subnet: cloud-run-access

  metamist:server:
    web_domain: metamist.populationgenomics.org.au
    oauth_client_config_secret_name: metamist-oauth-client-config 
    db_credentials_secret_name: metamist-server-db-credentials
    iap_audience: /projects/890472361088/global/backendServices/1657741685801176969
    
  metamist:migrations:
    db_credentials_secret_name: metamist-migration-db-credentials
    github_token_secret_name: metamist-github-token

