secretsprovider: gcpkms://projects/metamist-488300/locations/australia-southeast1/keyRings/metamist_pulumi_secrets_keyring/cryptoKeys/metamist_pulumi_secrets
encryptedkey: CiQAelOKiUKO55T9/L58gQl4yuSCU6VRJMcuNAh377Foxf1qJvwSSQDdXNuFPODn1KcT+V++wl3SjTi181KXWF1fggSVGR7FS/NRHHmQrq58ggRKDoWjWxI5nUMiy5yDILQWyOmfOikK/L25EdznGSQ=
config:
  gcp:project: metamist-488300
  gcp:billing_project: metamist-488300
  gcp:user_project_override: 'true'
  gcp:region: australia-southeast1

  metamist:
    common:
      vpc_network: metamist-db
      vpc_subnet: cloud-run-access
    server:
      web_domain: metamist.populationgenomics.org.au
      oauth_client_config_secret_name: metamist-oauth-client-config
      db_credentials_secret_name: metamist-server-db-credentials
      slack_token_secret_name: projects/1051897107465/secrets/slack-production-bot-token
      enable_gcp_logging: 'true'
      logging_level: DEBUG
      sample_prefix: XPG
      sample_check_offset: '1'
      environment: production
      seqr_url: https://seqr.populationgenomics.org.au
      seqr_audience: 1021400127367-9uc4sikfsm0vqo38q1g6rclj91mm501r.apps.googleusercontent.com
      seqr_map_location: gs://cpg-seqr-main-analysis/automation/
      seqr_slack_notification_channel: rd-seqr-sync-alerts
      sequencing_group_prefix: CPG
      sequencing_group_check_offset: '0'
      gcp_bq_aggreg_view: billing-admin-290403.billing_aggregate.aggregate_daily
      gcp_bq_aggreg_raw: billing-admin-290403.billing_aggregate.aggregate
      gcp_bq_aggreg_ext_view: billing-admin-290403.billing_aggregate.aggregate_daily_extended
      gcp_bq_budget_view: billing-admin-290403.billing.budget_by_project_monthly
      gcp_bq_billing_view: billing-admin-290403.billing.gcp_billing_daily_cost
      gcp_bq_batches_view: billing-admin-290403.billing_aggregate.aggregate_job_details
      metamist_gcp_project: sample-metadata
      oauth_audience: /projects/774248915715/global/backendServices/4615543739767186396
    migrations:
      db_credentials_secret_name: metamist-migration-db-credentials
      github_token_secret_name: metamist-github-token
