secretsprovider: gcpkms://projects/metamist-dev/locations/australia-southeast1/keyRings/metamist_pulumi_secrets_keyring/cryptoKeys/metamist_pulumi_secrets
encryptedkey: CiQAYMrX90C8cpGFk0qXnUC3u4YBTypgWbgqHlpZGn3MR+V+o04SSQBfR/wcygDTDTt05bHs7bdu++t9hmbK/Tl8rPlJplvPcWAwovk/TmBxSjALYJ55Vq+jkNkgAdRbZhFNTlBqJKj1aZ9HXps1fE0=
config:
  gcp:project: metamist-dev
  gcp:billing_project: metamist-dev
  gcp:user_project_override: 'true'
  gcp:region: australia-southeast1

  metamist:
    server:
      web_domain: metamist-dev.populationgenomics.org.au
      oauth_client_config_secret_name: metamist-dev-oauth-client-config
      db_credentials_secret_name: metamist-dev-server-db-credentials
      slack_token_secret_name: projects/1051897107465/secrets/slack-production-bot-token
      enable_gcp_logging: 'true'
      logging_level: INFO
      sample_prefix: XPGDEV
      sample_check_offset: '3'
      environment: development
      seqr_url: https://seqr-staging.populationgenomics.org.au
      seqr_audience: 1021400127367-40kj6v68nlps6unk6bgvh08r5o4djf6b.apps.googleusercontent.com
      seqr_map_location: gs://cpg-seqr-main-analysis/automation/
      sequencing_group_prefix: CPGDEV
      sequencing_group_check_offset: '1'
      gcp_bq_aggreg_view: billing-admin-290403.billing_aggregate.aggregate_daily
      gcp_bq_aggreg_raw: billing-admin-290403.billing_aggregate.aggregate
      gcp_bq_aggreg_ext_view: billing-admin-290403.billing_aggregate.aggregate_daily_extended
      gcp_bq_budget_view: billing-admin-290403.billing.budget_by_project_monthly
      gcp_bq_billing_view: billing-admin-290403.billing.gcp_billing_daily_cost
      gcp_bq_batches_view: billing-admin-290403.billing_aggregate.aggregate_job_details
      metamist_gcp_project: sample-metadata
      oauth_audience: /projects/774248915715/global/backendServices/2616078258375810936
    migrations:
      db_credentials_secret_name: metamist-dev-migration-db-credentials
      github_token_secret_name: metamist-dev-github-token

