secretsprovider: gcpkms://projects/metamist-488300/locations/australia-southeast1/keyRings/metamist_pulumi_secrets_keyring/cryptoKeys/metamist_pulumi_secrets
encryptedkey: CiQAelOKiUKO55T9/L58gQl4yuSCU6VRJMcuNAh377Foxf1qJvwSSQDdXNuFPODn1KcT+V++wl3SjTi181KXWF1fggSVGR7FS/NRHHmQrq58ggRKDoWjWxI5nUMiy5yDILQWyOmfOikK/L25EdznGSQ=
config:
  gcp:project: metamist-488300
  gcp:billing_project: metamist-488300
  gcp:user_project_override: 'true'
  gcp:region: australia-southeast1
  app:web-domain: metamist.populationgenomics.org.au
  app:api-domain: metamist-api.populationgenomics.org.au
  app:iap_audience: /projects/890472361088/global/backendServices/1657741685801176969