secretsprovider: gcpkms://projects/metamist-dev/locations/australia-southeast1/keyRings/metamist_pulumi_secrets_keyring/cryptoKeys/metamist_pulumi_secrets
encryptedkey: CiQAYMrX90C8cpGFk0qXnUC3u4YBTypgWbgqHlpZGn3MR+V+o04SSQBfR/wcygDTDTt05bHs7bdu++t9hmbK/Tl8rPlJplvPcWAwovk/TmBxSjALYJ55Vq+jkNkgAdRbZhFNTlBqJKj1aZ9HXps1fE0=
config:
  gcp:project: metamist-dev
  gcp:billing_project: metamist-dev
  gcp:user_project_override: 'true'
  gcp:region: australia-southeast1
  app:web-domain: metamist-dev.populationgenomics.org.au
  app:api-domain: metamist-api-dev.populationgenomics.org.au
  app:iap_audience: /projects/890472361088/global/backendServices/1657741685801176969
