secretsprovider: gcpkms://projects/metamist-488300/locations/australia-southeast1/keyRings/metamist_pulumi_secrets_keyring/cryptoKeys/metamist_pulumi_secrets
encryptedkey: CiQAelOKib7r37bkf9xVNzqQNklLr4t2XLHu7KQSbe/nI8b/LuUSSQDdXNuF7Kd7HipODcych9k/Myp14jGGVPhGXBn+I62n+x69dVdAUCpV0mf3OVhmxDq2pP+kTOzptPwkWfMxsS2R3zBMoHHhK6g=
config:
  gcp:project: metamist-488300
  gcp:billing_project: metamist-488300
  gcp:user_project_override: 'true'
  gcp:region: australia-southeast1
  app:web-domain: metamist.populationgenomics.org.au
  app:api-domain: metamist-api.populationgenomics.org.au
  app:iap_audience: /projects/890472361088/global/backendServices/1657741685801176969
