extend = "../../ruff.toml"
# Make sure linting/formatting changes don't break compatibility with
# python 3.10 which is the min supported version for the metamist python package
target-version = "py310"

[lint]
future-annotations = false