
services:
  postgres:
    build: .
    container_name: metamist_postgres
    environment:
      POSTGRES_USER: metamist_superuser
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-metamist_password}
      POSTGRES_DB: metamist
      DATABASE_URL: postgres://metamist_superuser:${POSTGRES_PASSWORD:-metamist_password}@localhost:5432/metamist?sslmode=disable&search_path=public,main,history
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - metamist_pg_data:/var/lib/postgresql
      - ./migrations:/db/migrations
volumes:
  metamist_pg_data:
