name: Lint
on:
  pull_request:
    type: [opened, synchronize]

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
      # used for generating API
      SM_DOCKER: samplemetadata:dev
    defaults:
      run:
        shell: bash -eo pipefail -l {0}
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Install uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e #v6.8.0
        with:
          activate-environment: true
          enable-cache: false
          version: 0.8.22 #uv version

      - name: Setup build env
        run: |
          set -euxo pipefail
          uv sync

      - name: 'install frontend deps'
        working-directory: ./web
        run: npm ci

      - name: 'check frontend formatting'
        working-directory: ./web
        run: npm run format:check

      - name: 'check frontend linting'
        working-directory: ./web
        run: npm run lint

      - name: Build + install packages
        run: |
          uv sync
          uv run regenerate_api.py

      - name: pre-commit
        #run: uv run pre-commit run --from-ref $GITHUB_BASE_REF --to-ref $GITHUB_REF
        #run: uv run pre-commit run --from-ref ${{ github.base_ref }} --to-ref ${{ github.head_ref }}
        run: |
          set -x
          echo x1 $GITHUB_BASE_REF
          echo x2 $GITHUB_REF
          echo x3 ${{ github.base_ref }}
          echo x4 ${{ github.head_ref }}
          echo x5 ${{ github.event.pull_request.base.sha }}
          echo x6 ${{ github.event.pull_request.head.sha }}
          git log -1 $GITHUB_BASE_REF || true
          git log -1 origin/$GITHUB_BASE_REF || true
          git log -1 $GITHUB_REF || true
          git log -1 ${{ github.event.pull_request.base.sha }} || true
          git log -1 ${{ github.event.pull_request.head.sha }} || true
          uv run pre-commit run --from-ref $GITHUB_BASE_REF --to-ref $GITHUB_REF
