name: Renovate
on:
  schedule:
    - cron: '0 0 * * Sun'
  push:
    branches:
      - dev
  workflow_dispatch:

permissions: {}

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.2.10
        with:
          token: '${{ steps.app-token.outputs.token }}'
          docker-user: root
          configurationFile: .github/renovate-config.json
        env:
          LOG_LEVEL: 'debug'
          RENOVATE_PLATFORM_COMMIT: 'true'
