name: Liquibase Schema Update via Cloud Run

on:
  workflow_dispatch:
    inputs:
      dbName:
        description: 'Database Instance'
        required: true
        type: choice
        options:
        - production
        - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: "projects/774248915715/locations/global/workloadIdentityPools/gh-deploy-pool/providers/gh-provider"
        service_account: "sample-metadata-deploy@sample-metadata.iam.gserviceaccount.com"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./db  # Set the context to the db directory to include project.xml
        file: ./deploy/Dockerfile
        push: true
        tags: gcr.io/sample-metadata/liquibase-job:latest
        build-args: |
          DB_NAME=${{ github.event.inputs.dbName }}

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v0.7.0
      with:
        service: liquibase-job
        image: gcr.io/sample-metadata/liquibase-job:latest
        region: australia-southeast1
        command: |
          gcloud run deploy liquibase-job \
            --image=gcr.io/sample-metadata/liquibase-job:latest \
            --update-env-vars=DB_NAME=${{ github.event.inputs.dbName }}

    - name: Cleanup
      if: always()
      uses: google-github-actions/delete-gcr@v0.4.0
      with:
        image: gcr.io/sample-metadata/liquibase-job:latest
